org: ${env:SERVERLESS_ORG}
service: ${env:SERVERLESS_SERVICE}

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION}
  iam:
    role: ${env:AWS_ROLE}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: "*"
          method: "*"

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${env:TABLE_NAME_USERS}
    MeetingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: MeetingId
            AttributeType: S
        KeySchema:
          - AttributeName: MeetingId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${env:TABLE_NAME_MEETINGS}
