org: "pettersson332"
service: "meetups"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: arn:aws:iam::676206943781:role/dev-db

functions:
  api:
    handler: handler.handler # Make sure to replace 'app' with the actual exported function in your handler.js
    events:
      - httpApi: # Using HTTP API Gateway
          path: "*" # Ensures it captures all paths

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: "users-meetings"
